name             'jenkins_wrapper_cookbook'
maintainer       'Jason Kulatunga'
maintainer_email 'jason@thesparktree.com'
license          'All rights reserved'
description      'Installs/Configures jenkins_wrapper_cookbook'
long_description 'Installs/Configures jenkins_wrapper_cookbook'
version          '0.1.0'

depends 'git'
depends 'java'
depends 'jenkins'
depends 'poise-python'
depends 'chef-client'
